// Final GATE CSE syllabus template — aligned with the official IIT syllabus
// (unchanged since the GATE 2021 revision) and standard textbooks:
//   Discrete Math ......... Rosen
//   Engg. Math ............ standard B.Tech math texts
//   Digital Logic ......... Mano
//   COA ................... Mano / Hamacher
//   PDS & Algorithms ...... CLRS + C (K&R)
//   TOC ................... Sipser / Ullman
//   Compiler Design ....... Dragon Book (Aho et al.)
//   OS .................... Silberschatz & Galvin
//   DBMS .................. Korth / Navathe
//   Networks .............. Kurose & Ross / Tanenbaum
//
// Used only to seed a brand-new user's Firestore document — after that,
// the user's own copy is the truth.

export const DEFAULT_SYLLABUS = {
  "General Aptitude": [
    "Verbal: grammar & sentence completion",
    "Verbal: reading comprehension",
    "Verbal: word analogies & vocabulary",
    "Quantitative: ratios, percentages, mixtures",
    "Quantitative: time-speed-distance & work",
    "Quantitative: permutations, combinations, probability basics",
    "Quantitative: data interpretation (tables, charts)",
    "Analytical: logical reasoning & puzzles",
    "Analytical: number & letter series",
    "Spatial: figure rotation, paper folding, patterns",
  ],

  "Discrete Mathematics": [
    "Propositional logic (connectives, truth tables, equivalences)",
    "First-order logic (quantifiers, inference)",
    "Sets & set operations",
    "Relations (properties, equivalence, closure)",
    "Functions (injective, surjective, bijective, composition)",
    "Partial orders & lattices",
    "Monoids & groups",
    "Counting: permutations & combinations, pigeonhole",
    "Recurrence relations (solving linear recurrences)",
    "Generating functions",
    "Graph basics: degree, handshaking, isomorphism",
    "Graph connectivity (cut vertices, components)",
    "Graph matching",
    "Graph coloring (chromatic number)",
    "Euler & Hamiltonian graphs, planarity",
  ],

  "Engineering Mathematics": [
    "Matrices & determinants",
    "System of linear equations (rank, consistency)",
    "Eigenvalues & eigenvectors",
    "LU decomposition",
    "Limits & continuity",
    "Differentiability, maxima & minima",
    "Mean value theorem",
    "Definite & improper integrals",
    "Probability axioms & conditional probability",
    "Bayes' theorem",
    "Random variables (discrete & continuous)",
    "Distributions: uniform, binomial, Poisson, normal, exponential",
    "Mean, median, mode, standard deviation",
    "Expectation & variance",
  ],

  "Digital Logic": [
    "Number systems & base conversions",
    "Binary codes (BCD, Gray, ASCII)",
    "Boolean algebra: laws & theorems",
    "Minimization: K-maps (up to 5 variables)",
    "Combinational: adders & subtractors",
    "Combinational: multiplexers & demultiplexers",
    "Combinational: encoders, decoders, comparators",
    "Sequential: latches & flip-flops (SR, JK, D, T)",
    "Sequential: counters (sync, async, ring, Johnson)",
    "Sequential: registers & shift registers",
    "Fixed-point representation & arithmetic",
    "Floating-point representation (IEEE 754)",
  ],

  "Computer Organization & Architecture": [
    "Machine instructions & instruction formats",
    "Addressing modes",
    "ALU & data-path design",
    "Control unit: hardwired vs microprogrammed",
    "Instruction pipelining (stages, speedup)",
    "Pipeline hazards (structural, data, control)",
    "Memory hierarchy overview",
    "Cache: mapping (direct, associative, set-assoc.)",
    "Cache: performance, write policies, multilevel",
    "Main memory (interleaving, DRAM basics)",
    "Secondary storage (disk structure, access time)",
    "I/O: programmed, interrupt-driven",
    "I/O: DMA",
  ],

  "Programming & Data Structures": [
    "C: operators, expressions, control flow",
    "C: pointers & arrays",
    "C: functions, parameter passing, scope",
    "C: structures & unions",
    "Recursion (tracing, stack behavior)",
    "Arrays (1D, 2D, address calculation)",
    "Stacks (applications: expressions, parentheses)",
    "Queues (circular, deque)",
    "Linked lists (singly, doubly, circular)",
    "Trees: traversals & properties",
    "Binary search trees (insert, delete, search)",
    "Binary heaps (build, heapify, priority queue)",
    "Graph representations (matrix, adjacency list)",
    "Hashing (hash functions, collision resolution)",
  ],

  "Algorithms": [
    "Asymptotic notation (O, Ω, Θ)",
    "Recurrence solving & Master theorem",
    "Sorting: comparison-based (merge, quick, heap)",
    "Sorting: non-comparison (counting, radix, bucket)",
    "Searching (binary search & variants)",
    "Divide and conquer technique",
    "Greedy technique (activity selection, Huffman)",
    "Dynamic programming (LCS, knapsack, matrix chain)",
    "Graph traversals: BFS & DFS (and applications)",
    "Minimum spanning trees (Prim, Kruskal)",
    "Shortest paths: Dijkstra",
    "Shortest paths: Bellman-Ford & Floyd-Warshall",
    "Topological sort & strongly connected components",
    "P, NP, NP-complete, NP-hard",
  ],

  "Theory of Computation": [
    "DFA & NFA (construction, equivalence)",
    "Minimization of DFA",
    "Regular expressions",
    "Closure & decision properties of regular languages",
    "Pumping lemma for regular languages",
    "Context-free grammars (derivations, ambiguity)",
    "CFG simplification & normal forms (CNF)",
    "Pushdown automata",
    "Pumping lemma for CFLs, closure properties",
    "Turing machines (variants, configurations)",
    "Recursive & recursively enumerable languages",
    "Decidability & undecidability (reductions)",
  ],

  "Compiler Design": [
    "Phases of a compiler",
    "Lexical analysis (tokens, regex, finite automata)",
    "Top-down parsing: LL(1), FIRST & FOLLOW",
    "Bottom-up parsing: LR(0), SLR, LALR",
    "Syntax-directed translation (attributes, SDD/SDT)",
    "Intermediate code: three-address code",
    "Runtime environments (activation records, stack)",
    "Local optimization (basic blocks, DAG)",
    "Data flow analysis: constant propagation",
    "Data flow analysis: liveness analysis",
    "Data flow analysis: common subexpression elimination",
  ],

  "Operating Systems": [
    "System calls & OS structure",
    "Processes (states, PCB, context switch)",
    "Threads (user vs kernel level)",
    "CPU scheduling algorithms (FCFS, SJF, RR, priority)",
    "Inter-process communication",
    "Synchronization: race conditions & critical section",
    "Synchronization: semaphores, mutexes, monitors",
    "Classic problems (producer-consumer, readers-writers)",
    "Deadlock: conditions & resource allocation graph",
    "Deadlock: prevention, avoidance (Banker's), detection",
    "Memory management: paging & page tables",
    "Memory management: segmentation",
    "Virtual memory: demand paging, page replacement",
    "Thrashing & working set",
    "File systems (allocation, inodes, directories)",
    "I/O scheduling (disk scheduling algorithms)",
  ],

  "Databases": [
    "ER model (entities, relationships, cardinality)",
    "ER to relational mapping",
    "Relational model & integrity constraints",
    "Relational algebra",
    "Tuple relational calculus",
    "SQL: queries, joins, aggregation",
    "SQL: nested queries & set operations",
    "Functional dependencies & closures",
    "Normal forms (1NF, 2NF, 3NF, BCNF)",
    "Decomposition (lossless join, dependency preservation)",
    "File organization & indexing (primary, secondary)",
    "B-trees & B+ trees",
    "Transactions & ACID properties",
    "Concurrency control (schedules, serializability, locking)",
    "Recovery basics (log-based)",
  ],

  "Computer Networks": [
    "Layering: OSI & TCP/IP protocol stacks",
    "Switching: circuit, packet, virtual circuit",
    "Data link: framing & error detection (parity, CRC)",
    "Medium Access Control (ALOHA, CSMA/CD)",
    "Ethernet & bridging (switches, spanning tree basics)",
    "Routing: shortest path & flooding",
    "Routing: distance vector & link state",
    "IPv4 addressing & CIDR notation",
    "Subnetting & supernetting",
    "IP fragmentation",
    "IP support protocols (ARP, DHCP, ICMP)",
    "Network Address Translation (NAT)",
    "Transport: UDP",
    "Transport: TCP (connection, reliability, flow control)",
    "TCP congestion control",
    "Sockets basics",
    "Application layer: DNS, SMTP, HTTP, FTP, Email",
  ],
};